strictness: veryhigh
doc-warnings: true
ignore-paths:
  - __init__.py
member-warnings: true
mypy:
  run: true
  options:
    ignore-missing-imports: true
max-line-length: 100
pep257:
  disable:
    - D203  # Don't require blank line before class docstrings
    - D213  # Don't require summaries to start on the second line