language: python
sudo: false
python:
  - "3.6"
install:
  - pip install -r requirements.txt -q
  - pip install -r requirements-dev.txt -q

script:
  - prospector --with-tool mypy
  - cd tests && pytest