[text]
train_path = "../dataset-sentence-splits/gold/gold"
dev_path = "../dataset-sentence-splits/gold/gold"
test_path = "../dataset-sentence-splits/gold/gold"

[lstm]
embedding_size = 256
hidden_size = 256
output_size = 2

[training]
batch_size = 32
epochs = 10
model_file = "./best_ud_german_model.pt"
learning_rate = 0.001

[deep_eos]
left_ws = 4
right_ws = 4

[prediction]
dev_tagged_file = "own_dataset_dev_tagged.txt"
test_tagged_file = "own_dataset_test_tagged.txt"
eos_marker = "</eos>"
